version: '1.0.{build}'
image: Visual Studio 2017 Preview
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Get a later version of Node.js
  - ps: Install-Product node 6.11.5
  - cmd: npm -v
  # Install repo specific stuff here
  - cmd: cd ./Ballast.Core
  - cmd: npm install
  - cmd: cd ../Ballast.Client
  - cmd: npm install
  - cmd: cd ../Ballast.Web
  - cmd: npm install
  - cmd: cd ../
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Ballast.Core/Ballast.Core.csproj --verbosity m
  - cmd: dotnet restore ./Ballast.Web/Ballast.Web.csproj --verbosity m
build_script:
  # output will be in ./Ballast.Web/bin/debug/netcoreapp2.1/publish
  - cmd: dotnet publish ./Ballast.Web/Ballast.Web.csproj 
after_build:
  # For once the build has completed
artifacts:
 - path: '\Ballast.Web\bin\Debug\netcoreapp2.1\publish'
   name: Ballast
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: cd ./Ballast.Core
  - cmd: npm test
  - cmd: cd ../Ballast.Client
  - cmd: npm test
  - cmd: cd ../Ballast.Web
  - cmd: npm test
on_finish :
  # any cleanup in here
deploy: off