version: '1.0.{build}'
image: Visual Studio 2017 Preview
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Get a later version of Node.js
  - ps: Install-Product node 9.9.0
  - cmd: npm -g install npm@5.7.1
  - cmd: npm -v
  # Install repo specific stuff here
  - cmd: cd ./ballast-core/npm
  - cmd: npm install
  - cmd: cd ../../ballast-client/npm
  - cmd: npm install
  - cmd: cd ../../ballast-web/npm
  - cmd: npm install
  - cmd: cd ../../
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./ballast-core/dotnet/Ballast.Core.csproj --verbosity m
  - cmd: dotnet restore ./ballast-server/dotnet/Ballast.Server.csproj --verbosity m
  - cmd: dotnet restore ./ballast-web/dotnet/Ballast.Web.csproj --verbosity m
build_script:
  # output will be in ./Ballast.Web/bin/debug/netcoreapp2.2/publish
  - cmd: dotnet publish ./ballast-web/dotnet/Ballast.Web.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\ballast-web\dotnet\bin\Debug\netcoreapp2.2\publish'
   name: Ballast
   type: Zip
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: cd ./ballast-core/npm
  - cmd: npm test local-event-bus # TODO:  Run all tests
  # - cmd: cd ../ballast-client
  # - cmd: npm test
  - cmd: cd ../../
on_finish :
  # any cleanup in here
deploy: off