version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - add-lerna-and-gulp
init:
  # Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Get a later version of Node.js / npm
  - ps: Install-Product node 12.9.1
  - cmd: node --version
  - cmd: npm -g install npm@latest
  - cmd: npm -v
  # Install build tooling
  - cmd: npm -g install lerna gulp
  - cmd: lerna -v
  - cmd: gulp -v
  # Build npm
  - cmd: lerna bootstrap
  # Build dotnet (web)
  - cmd: cd ./ballast-web/dotnet
  - cmd: dotnet build
  - cmd: cd ../../
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ballast.sln
build_script:
  # output will be in ./Ballast.Web/bin/debug/netcoreapp2.2/publish
  - cmd: dotnet publish ./ballast-web/dotnet/Ballast.Web.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\ballast-web\dotnet\bin\Debug\netcoreapp2.2\publish'
   name: Ballast
   type: Zip
clone_depth: 1
test_script:
  - cmd: cd ./ballast-core/npm
  - cmd: npm test
  - cmd: cd ../../ballast-client/npm
  - cmd: npm test
  - cmd: cd ../../ballast-ui/npm
  - cmd: npm test
  - cmd: cd ../../ballast-web/npm
  - cmd: npm test
  - cmd: cd ../../
on_finish :
  # any cleanup in here
deploy: off